// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGJ1elSbmHDpaH8HHxA-6kYrYQsthADQ',
    appId: '1:217829261292:web:ecd0fa8ee5bca320508ac9',
    messagingSenderId: '217829261292',
    projectId: 'uber-clone-c3f9a',
    authDomain: 'uber-clone-c3f9a.firebaseapp.com',
    storageBucket: 'uber-clone-c3f9a.appspot.com',
    measurementId: 'G-WWFY9PCJDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkHY-1AIH2Sk3YjGGs-1QMKXSKqEtdAjY',
    appId: '1:217829261292:android:c988dc7fbdb6eea0508ac9',
    messagingSenderId: '217829261292',
    projectId: 'uber-clone-c3f9a',
    storageBucket: 'uber-clone-c3f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-bCsp3pxeghZKqcYajV6hDbHXYHCT7k',
    appId: '1:217829261292:ios:1a4f565f3a9c2924508ac9',
    messagingSenderId: '217829261292',
    projectId: 'uber-clone-c3f9a',
    storageBucket: 'uber-clone-c3f9a.appspot.com',
    iosClientId: '217829261292-qdmn7i23nlb66o8uncrt9jah3hkkl78k.apps.googleusercontent.com',
    iosBundleId: 'com.reiguedal.uberclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV-bCsp3pxeghZKqcYajV6hDbHXYHCT7k',
    appId: '1:217829261292:ios:1a4f565f3a9c2924508ac9',
    messagingSenderId: '217829261292',
    projectId: 'uber-clone-c3f9a',
    storageBucket: 'uber-clone-c3f9a.appspot.com',
    iosClientId: '217829261292-qdmn7i23nlb66o8uncrt9jah3hkkl78k.apps.googleusercontent.com',
    iosBundleId: 'com.reiguedal.uberclone',
  );
}
